language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
script:
- "./gradlew clean build"
deploy:
  provider: releases
  api_key: "$OUATH_KEY"
  file_glob: true
  file: "{$TRAVIS_BUILD_DIR}/app/build/outputs/apk/toz-prod-debug.apk"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: TtdaDZsiseuy9h92C15h4D+F29G1miBoaLgGNGomVm+s4KGaTnKPtFnV5onUY0KxSkXj9heH13Wp0GvMAzEyWE3j8N59RNoMcer1NVcnWqK7lD4g5KZx2AQ+PUaPSTrc27hNin6HzD9WCH9EJviUsvpWuqk5+Enuy7eLDqGa8CHqByDHvFi81UkSWddMLFLF0lpsMIm9h2Sj1LnoQVNNNaf+gHy6N4qT3+WafV0f+1xL8t4QeYb+KO9k0/oWIggkHoYenCSPL8+BYQz/xxCqf2nm9awFDdyfL9Jl8u4ize8q80hCAa0iWLLGE865a0A5JO7fFQ/3Yaan7BOROg2oP/+SO2ZUuZDb/zHJ/ShIJOGgDIfHrrEs+ZeXhQpYZxvnktrWL7+kRQM8Rbmgjf1Jjd/a/gSHhsYre6oTBggAIz60kHK7vraNzKQ1Ozwg/+EHoMjD+IU2vHb2bAWdjeG87maomTJsq/tqQXfvNiN9NrCO2KwSbnLacC0VzY3G0NO9l39C7mKjA9mT5wguruzoywD6lbJRzwn0KShnXfELBsC1K6GD/FNFYdAzp7s8X50sDOdSG2YdVBHxijuaxD0odhLebHzQLuOkZ0X14vpZCNcDrIoJj2LfOQnAEOpXfcSbVxoy64/UjBMc3k+bbFbBtI30GQIyeSmPsJgwE0VNyhw=
notifications:
  slack:
    secure: d3hnnnhFahhCGqTfkdzVwYYwSw0efe1SoHyL8RTeG2ZYFLYEzWBjlSrRnH75GTi7KWONEUe61kvKY2d8WhcKqs3D6Ik6sSo+nOLuayXBnPjBzd5adRXnClWtj+SHKZj4XgJkNRPwPPPz7KOmqlQ7PKx+dEbhNYK0GpUIuTKTrLJhnTJ77JOlDtywn6VndqH+ev63cc56l+Ms58sOU7Y0HPuf8Ld4z+A9PcV/FPDoONNzhyKclrBVqSPrz3KQJQCEDeVNG05IIayc1jL5duWX1o4LI+nTSs2VNdV5dh23JgKKA6RL2YdMo3x2q+ecyyoec7E6LgDjsqmvg/QH2CkQ+XsctVLfyyqdJ5GreblM9LhBHpMgeuGlYui1kiXVC9gE6WTqZUH4rbcTTxCrK2ClM+DX8HlN/Ew51eCTFAcigfacu9bclAzfXM645Ww0fxrQ482tLNAUnnTPG6qdOks7LNlGO9RcZswhhavgqDitCwjKb0Tj+y348oPcL1rI3QRQVEbOiWiqHqsdvJCGBzVTCT9z+xk6nKpo12EKgPv3fM4cxwvVkHVpJ9QTLgjpBtboRdx6pCb2feppUkK/m7hEqR5i7vCxuqcy4eMe8OFz1bCMAn854otmE7cDorlkx4085eHvXRVnc4MfUjGhzXKfaQh1fVPuutgOjaogKS5Uzz4=
    on_success: change
    on_failure: change
    on_start: never